# h-params

lr: 0.001
weight_decay: 0.0001
input_size: 1024
batch_size: 4
sched: poly # choices from "cosine", "onecycle", "poly"

# pretrain and freezing
freeze_backbone: False
pretrained: True

# computing
rotation: True # Use rotation
device: null
workers: 0
amp: False # Automatic Mixed Precision
eval_straight: False # Use simpler evaluate (speed-up val)

# other settings
find_lr: False
early_stop: False
early_stop_epochs: 5
early_stop_delta: 0.01
